/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.ourdsl.idea.lang.psi;

import com.intellij.psi.util.PsiModificationTracker;
import org.eclipse.xtext.psi.BaseXtextCodeBlockModificationListener;
import org.xtext.example.ourdsl.idea.lang.OurDslLanguage;

public class OurDslCodeBlockModificationListener extends BaseXtextCodeBlockModificationListener {

	public OurDslCodeBlockModificationListener(PsiModificationTracker psiModificationTracker) {
		super(OurDslLanguage.INSTANCE, psiModificationTracker);
	}

}
