/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.yourdsl.idea.lang.psi.impl;

import com.intellij.openapi.fileTypes.FileType;
import com.intellij.psi.FileViewProvider;
import org.eclipse.xtext.psi.impl.BaseXtextFile;
import org.xtext.example.yourdsl.idea.lang.YourDslFileType;
import org.xtext.example.yourdsl.idea.lang.YourDslLanguage;

public final class YourDslFileImpl extends BaseXtextFile {

	public YourDslFileImpl(FileViewProvider viewProvider) {
		super(viewProvider, YourDslLanguage.INSTANCE);
	}

	@Override
	public FileType getFileType() {
		return YourDslFileType.INSTANCE;
	}
}
