/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.yourdsl.idea.completion;

import org.eclipse.xtext.common.idea.completion.TerminalsCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractYourDslCompletionContributor extends TerminalsCompletionContributor {
	public AbstractYourDslCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
