/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.yourdsl.idea.lang


class YourDslFileType extends AbstractYourDslFileType {
	public static final YourDslFileType INSTANCE = new YourDslFileType()
	
	new() {
		super(YourDslLanguage.INSTANCE)
	}
}
