/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.yourdsl.ide.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.yourdsl.services.YourDslGrammarAccess;

public class YourDslParser extends AbstractContentAssistParser {
	
	@Inject
	private YourDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.yourdsl.ide.contentassist.antlr.internal.InternalYourDslParser createParser() {
		org.xtext.example.yourdsl.ide.contentassist.antlr.internal.InternalYourDslParser result = new org.xtext.example.yourdsl.ide.contentassist.antlr.internal.InternalYourDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getYourGreetingAccess().getGroup(), "rule__YourGreeting__Group__0");
					put(grammarAccess.getModelAccess().getGreetingsAssignment(), "rule__Model__GreetingsAssignment");
					put(grammarAccess.getYourGreetingAccess().getNameAssignment_1(), "rule__YourGreeting__NameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.yourdsl.ide.contentassist.antlr.internal.InternalYourDslParser typedParser = (org.xtext.example.yourdsl.ide.contentassist.antlr.internal.InternalYourDslParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public YourDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(YourDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
