/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.yourdsl.idea.lang;

import com.intellij.openapi.fileTypes.FileTypeConsumer;
import com.intellij.openapi.fileTypes.FileTypeFactory;
import org.jetbrains.annotations.NotNull;

public class YourDslFileTypeFactory extends FileTypeFactory {

	@Override
	public void createFileTypes(@NotNull FileTypeConsumer consumer) {
		consumer.consume(YourDslFileType.INSTANCE, AbstractYourDslFileType.DEFAULT_EXTENSION);
	}

}
