/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.yourdsl.idea.lang;

import com.intellij.psi.tree.IFileElementType;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.idea.lang.IElementTypeProvider;
import org.eclipse.xtext.psi.stubs.XtextFileElementType;
import org.eclipse.xtext.psi.stubs.XtextFileStub;
import org.eclipse.xtext.psi.tree.IGrammarAwareElementType;
import org.xtext.example.yourdsl.idea.lang.psi.impl.YourDslFileImpl;
import org.xtext.example.yourdsl.services.YourDslGrammarAccess;

public class YourDslElementTypeProvider implements IElementTypeProvider {

	public static final IFileElementType FILE_TYPE = new XtextFileElementType<XtextFileStub<YourDslFileImpl>>(YourDslLanguage.INSTANCE);

	private static final Map<EObject, IGrammarAwareElementType> GRAMMAR_ELEMENT_TYPE = new HashMap<EObject, IGrammarAwareElementType>();

	private static IGrammarAwareElementType associate(IGrammarAwareElementType grammarAwareElementType) {
		GRAMMAR_ELEMENT_TYPE.put(grammarAwareElementType.getGrammarElement(), grammarAwareElementType);
		return grammarAwareElementType;
	}

	private static final YourDslGrammarAccess GRAMMAR_ACCESS = YourDslLanguage.INSTANCE.getInstance(YourDslGrammarAccess.class);

	private static class ModelFactory {
		public static IGrammarAwareElementType createModelElementType() {
			return new IGrammarAwareElementType("Model_ELEMENT_TYPE", YourDslLanguage.INSTANCE, GRAMMAR_ACCESS.getModelRule());
		}
		public static IGrammarAwareElementType createModel_GreetingsAssignmentElementType() {
			return new IGrammarAwareElementType("Model_GreetingsAssignment_ELEMENT_TYPE", YourDslLanguage.INSTANCE, GRAMMAR_ACCESS.getModelAccess().getGreetingsAssignment());
		}
		public static IGrammarAwareElementType createModel_GreetingsYourGreetingParserRuleCall_0ElementType() {
			return new IGrammarAwareElementType("Model_GreetingsYourGreetingParserRuleCall_0_ELEMENT_TYPE", YourDslLanguage.INSTANCE, GRAMMAR_ACCESS.getModelAccess().getGreetingsYourGreetingParserRuleCall_0());
		}
	}

	public static final IGrammarAwareElementType Model_ELEMENT_TYPE = associate(ModelFactory.createModelElementType());

	public static final IGrammarAwareElementType Model_GreetingsAssignment_ELEMENT_TYPE = associate(ModelFactory.createModel_GreetingsAssignmentElementType());

	public static final IGrammarAwareElementType Model_GreetingsYourGreetingParserRuleCall_0_ELEMENT_TYPE = associate(ModelFactory.createModel_GreetingsYourGreetingParserRuleCall_0ElementType());

	private static class YourGreetingFactory {
		public static IGrammarAwareElementType createYourGreetingElementType() {
			return new IGrammarAwareElementType("YourGreeting_ELEMENT_TYPE", YourDslLanguage.INSTANCE, GRAMMAR_ACCESS.getYourGreetingRule());
		}
		public static IGrammarAwareElementType createYourGreeting_GroupElementType() {
			return new IGrammarAwareElementType("YourGreeting_Group_ELEMENT_TYPE", YourDslLanguage.INSTANCE, GRAMMAR_ACCESS.getYourGreetingAccess().getGroup());
		}
		public static IGrammarAwareElementType createYourGreeting_YourdslKeyword_0ElementType() {
			return new IGrammarAwareElementType("YourGreeting_YourdslKeyword_0_ELEMENT_TYPE", YourDslLanguage.INSTANCE, GRAMMAR_ACCESS.getYourGreetingAccess().getYourdslKeyword_0());
		}
		public static IGrammarAwareElementType createYourGreeting_NameAssignment_1ElementType() {
			return new IGrammarAwareElementType("YourGreeting_NameAssignment_1_ELEMENT_TYPE", YourDslLanguage.INSTANCE, GRAMMAR_ACCESS.getYourGreetingAccess().getNameAssignment_1());
		}
		public static IGrammarAwareElementType createYourGreeting_NameIDTerminalRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("YourGreeting_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE", YourDslLanguage.INSTANCE, GRAMMAR_ACCESS.getYourGreetingAccess().getNameIDTerminalRuleCall_1_0());
		}
	}

	public static final IGrammarAwareElementType YourGreeting_ELEMENT_TYPE = associate(YourGreetingFactory.createYourGreetingElementType());

	public static final IGrammarAwareElementType YourGreeting_Group_ELEMENT_TYPE = associate(YourGreetingFactory.createYourGreeting_GroupElementType());

	public static final IGrammarAwareElementType YourGreeting_YourdslKeyword_0_ELEMENT_TYPE = associate(YourGreetingFactory.createYourGreeting_YourdslKeyword_0ElementType());

	public static final IGrammarAwareElementType YourGreeting_NameAssignment_1_ELEMENT_TYPE = associate(YourGreetingFactory.createYourGreeting_NameAssignment_1ElementType());

	public static final IGrammarAwareElementType YourGreeting_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE = associate(YourGreetingFactory.createYourGreeting_NameIDTerminalRuleCall_1_0ElementType());

	@Override
	public IFileElementType getFileType() {
		return FILE_TYPE;
	}

	@Override
	public IGrammarAwareElementType findElementType(EObject grammarElement) {
		return GRAMMAR_ELEMENT_TYPE.get(grammarElement);
	}
	
	public IGrammarAwareElementType getModelElementType() {
		return Model_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getModel_GreetingsAssignmentElementType() {
		return Model_GreetingsAssignment_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getModel_GreetingsYourGreetingParserRuleCall_0ElementType() {
		return Model_GreetingsYourGreetingParserRuleCall_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getYourGreetingElementType() {
		return YourGreeting_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getYourGreeting_GroupElementType() {
		return YourGreeting_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getYourGreeting_YourdslKeyword_0ElementType() {
		return YourGreeting_YourdslKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getYourGreeting_NameAssignment_1ElementType() {
		return YourGreeting_NameAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getYourGreeting_NameIDTerminalRuleCall_1_0ElementType() {
		return YourGreeting_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE;
	}

}
