/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.yourdsl.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class YourDslLanguage extends AbstractXtextLanguage{

	public static final YourDslLanguage INSTANCE = new YourDslLanguage();

	private YourDslLanguage() {
		super("org.xtext.example.yourdsl.YourDsl");
	}

}
