/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.yourdsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class YourDslStandaloneSetup extends YourDslStandaloneSetupGenerated {

	def static void doSetup() {
		new YourDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}

}
