/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.yourdsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class YourDslRuntimeModule extends AbstractYourDslRuntimeModule {
}
