/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.yourdsl.idea;

import com.intellij.openapi.extensions.ExtensionFactory;
import org.xtext.example.yourdsl.idea.lang.YourDslLanguage;

public class YourDslExtensionFactory implements ExtensionFactory {
	@Override
	public Object createInstance(String factoryArgument, String implementationClass) {
		Class<?> clazz;
		try {
			clazz = Class.forName(implementationClass);
		} catch (ClassNotFoundException e) {
			throw new IllegalArgumentException("Couldn't load "+implementationClass, e);
		}
		return YourDslLanguage.INSTANCE.<Object> getInstance(clazz);
	}
}
