/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.yourdsl.web;

import com.google.inject.Binder;
import com.google.inject.Provider;
import com.google.inject.name.Names;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtext.ide.LexerIdeBindings;
import org.eclipse.xtext.ide.editor.contentassist.antlr.IContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
import org.eclipse.xtext.web.server.DefaultWebModule;
import org.xtext.example.yourdsl.ide.contentassist.antlr.YourDslParser;
import org.xtext.example.yourdsl.ide.contentassist.antlr.internal.InternalYourDslLexer;

/**
 * Manual modifications go to {@link YourDslWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractYourDslWebModule extends DefaultWebModule {

	public AbstractYourDslWebModule(Provider<ExecutorService> executorServiceProvider) {
		super(executorServiceProvider);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.web.WebIntegrationFragment
	public void configureContentAssistLexer(Binder binder) {
		binder.bind(Lexer.class).annotatedWith(Names.named(LexerIdeBindings.CONTENT_ASSIST)).to(InternalYourDslLexer.class);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.web.WebIntegrationFragment
	public Class<? extends IContentAssistParser> bindIContentAssistParser() {
		return YourDslParser.class;
	}
	
}
