/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.yourdsl.idea.highlighting;

import org.eclipse.xtext.idea.highlighting.AbstractColorSettingsPage;
import org.xtext.example.yourdsl.idea.lang.YourDslLanguage;

public class YourDslBaseColorSettingsPage extends AbstractColorSettingsPage {
	
	public YourDslBaseColorSettingsPage() {
		YourDslLanguage.INSTANCE.injectMembers(this);
	}

	@Override
	public String getDisplayName() {
		return YourDslLanguage.INSTANCE.getDisplayName();
	}
}
