/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.yourdsl.idea.highlighting;

import org.eclipse.xtext.idea.highlighting.SemanticHighlightVisitor;
import org.xtext.example.yourdsl.idea.lang.YourDslLanguage;

public class YourDslSemanticHighlightVisitor extends SemanticHighlightVisitor {
	public YourDslSemanticHighlightVisitor() {
		YourDslLanguage.INSTANCE.injectMembers(this);
	}
}
