/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.ourdsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class OurDslStandaloneSetup extends OurDslStandaloneSetupGenerated {

	def static void doSetup() {
		new OurDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}

}
