/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.yourdsl.idea.lang.psi;

import com.intellij.psi.util.PsiModificationTracker;
import org.eclipse.xtext.psi.BaseXtextCodeBlockModificationListener;
import org.xtext.example.yourdsl.idea.lang.YourDslLanguage;

public class YourDslCodeBlockModificationListener extends BaseXtextCodeBlockModificationListener {

	public YourDslCodeBlockModificationListener(PsiModificationTracker psiModificationTracker) {
		super(YourDslLanguage.INSTANCE, psiModificationTracker);
	}

}
