/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.ourdsl.ide.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.ourdsl.services.OurDslGrammarAccess;

public class OurDslParser extends AbstractContentAssistParser {
	
	@Inject
	private OurDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.ourdsl.ide.contentassist.antlr.internal.InternalOurDslParser createParser() {
		org.xtext.example.ourdsl.ide.contentassist.antlr.internal.InternalOurDslParser result = new org.xtext.example.ourdsl.ide.contentassist.antlr.internal.InternalOurDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getGreetingAccess().getGroup(), "rule__Greeting__Group__0");
					put(grammarAccess.getModelAccess().getGreetingsAssignment(), "rule__Model__GreetingsAssignment");
					put(grammarAccess.getGreetingAccess().getNameAssignment_1(), "rule__Greeting__NameAssignment_1");
					put(grammarAccess.getGreetingAccess().getDslOneAssignment_3(), "rule__Greeting__DslOneAssignment_3");
					put(grammarAccess.getGreetingAccess().getDslTwoAssignment_5(), "rule__Greeting__DslTwoAssignment_5");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.ourdsl.ide.contentassist.antlr.internal.InternalOurDslParser typedParser = (org.xtext.example.ourdsl.ide.contentassist.antlr.internal.InternalOurDslParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public OurDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(OurDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
