/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.ourdsl.idea;

import com.intellij.openapi.extensions.ExtensionFactory;
import org.xtext.example.ourdsl.idea.lang.OurDslLanguage;

public class OurDslExtensionFactory implements ExtensionFactory {
	@Override
	public Object createInstance(String factoryArgument, String implementationClass) {
		Class<?> clazz;
		try {
			clazz = Class.forName(implementationClass);
		} catch (ClassNotFoundException e) {
			throw new IllegalArgumentException("Couldn't load "+implementationClass, e);
		}
		return OurDslLanguage.INSTANCE.<Object> getInstance(clazz);
	}
}
