/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.ourdsl.idea.facet;

import com.intellij.facet.Facet;
import com.intellij.facet.FacetTypeId;
import org.eclipse.xtext.idea.facet.AbstractFacetType;
import org.xtext.example.ourdsl.idea.lang.OurDslLanguage;

public class OurDslFacetType extends AbstractFacetType<OurDslFacetConfiguration> {

	public static final FacetTypeId<Facet<OurDslFacetConfiguration>> TYPEID = new FacetTypeId<Facet<OurDslFacetConfiguration>>("org.xtext.example.ourdsl.OurDsl");

	public OurDslFacetType() {
		super(TYPEID, "org.xtext.example.ourdsl.OurDsl", "OurDsl");
		OurDslLanguage.INSTANCE.injectMembers(this);
	}
}
