/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.mydsl.idea.lang


class MyDslFileType extends AbstractMyDslFileType {
	public static final MyDslFileType INSTANCE = new MyDslFileType()
	
	new() {
		super(MyDslLanguage.INSTANCE)
	}
}
