/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.ourdsl.idea.lang.psi.impl;

import com.intellij.openapi.fileTypes.FileType;
import com.intellij.psi.FileViewProvider;
import org.eclipse.xtext.psi.impl.BaseXtextFile;
import org.xtext.example.ourdsl.idea.lang.OurDslFileType;
import org.xtext.example.ourdsl.idea.lang.OurDslLanguage;

public final class OurDslFileImpl extends BaseXtextFile {

	public OurDslFileImpl(FileViewProvider viewProvider) {
		super(viewProvider, OurDslLanguage.INSTANCE);
	}

	@Override
	public FileType getFileType() {
		return OurDslFileType.INSTANCE;
	}
}
