/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.ourdsl.idea.highlighting;

import org.eclipse.xtext.idea.highlighting.AbstractColorSettingsPage;
import org.xtext.example.ourdsl.idea.lang.OurDslLanguage;

public class OurDslBaseColorSettingsPage extends AbstractColorSettingsPage {
	
	public OurDslBaseColorSettingsPage() {
		OurDslLanguage.INSTANCE.injectMembers(this);
	}

	@Override
	public String getDisplayName() {
		return OurDslLanguage.INSTANCE.getDisplayName();
	}
}
