/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.ourdsl.idea.highlighting;

import org.eclipse.xtext.idea.highlighting.SemanticHighlightVisitor;
import org.xtext.example.ourdsl.idea.lang.OurDslLanguage;

public class OurDslSemanticHighlightVisitor extends SemanticHighlightVisitor {
	public OurDslSemanticHighlightVisitor() {
		OurDslLanguage.INSTANCE.injectMembers(this);
	}
}
