/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.yourdsl.idea.lang.parser;

import com.google.inject.Inject;
import com.intellij.lang.PsiBuilder;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import org.antlr.runtime.TokenStream;
import org.eclipse.xtext.idea.parser.AbstractPsiAntlrParser;
import org.eclipse.xtext.idea.parser.AbstractXtextPsiParser;
import org.xtext.example.yourdsl.idea.lang.YourDslElementTypeProvider;
import org.xtext.example.yourdsl.idea.parser.antlr.internal.PsiInternalYourDslParser;
import org.xtext.example.yourdsl.services.YourDslGrammarAccess;

public class YourDslPsiParser extends AbstractXtextPsiParser {
	private static final Set<String> INITIAL_HIDDEN_TOKENS = new HashSet<String>(Arrays.asList("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT"));
	
	@Inject 
	private YourDslGrammarAccess grammarAccess;

	@Inject 
	private YourDslElementTypeProvider elementTypeProvider;

	@Override
	protected AbstractPsiAntlrParser createParser(PsiBuilder builder, TokenStream tokenStream) {
		return new PsiInternalYourDslParser(builder, tokenStream, elementTypeProvider, grammarAccess);
	}
	@Override
	protected Set<String> getInitialHiddenTokens() {
		return INITIAL_HIDDEN_TOKENS;
	}
}
