/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.ourdsl.idea.completion

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage
import org.xtext.example.ourdsl.idea.lang.OurDslLanguage

class OurDslCompletionContributor extends AbstractOurDslCompletionContributor {
	new() {
		this(OurDslLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
