/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.yourdsl.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class YourDslIdeaModule extends AbstractYourDslIdeaModule {
}
