/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.yourdsl.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class YourDslIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new YourDslStandaloneSetupIdea().createInjector
	}

}
