/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.mydsl.idea.lang;

import com.intellij.psi.tree.IFileElementType;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.idea.lang.IElementTypeProvider;
import org.eclipse.xtext.psi.stubs.XtextFileElementType;
import org.eclipse.xtext.psi.stubs.XtextFileStub;
import org.eclipse.xtext.psi.tree.IGrammarAwareElementType;
import org.xtext.example.mydsl.idea.lang.psi.impl.MyDslFileImpl;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslElementTypeProvider implements IElementTypeProvider {

	public static final IFileElementType FILE_TYPE = new XtextFileElementType<XtextFileStub<MyDslFileImpl>>(MyDslLanguage.INSTANCE);

	private static final Map<EObject, IGrammarAwareElementType> GRAMMAR_ELEMENT_TYPE = new HashMap<EObject, IGrammarAwareElementType>();

	private static IGrammarAwareElementType associate(IGrammarAwareElementType grammarAwareElementType) {
		GRAMMAR_ELEMENT_TYPE.put(grammarAwareElementType.getGrammarElement(), grammarAwareElementType);
		return grammarAwareElementType;
	}

	private static final MyDslGrammarAccess GRAMMAR_ACCESS = MyDslLanguage.INSTANCE.getInstance(MyDslGrammarAccess.class);

	private static class ModelFactory {
		public static IGrammarAwareElementType createModelElementType() {
			return new IGrammarAwareElementType("Model_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getModelRule());
		}
		public static IGrammarAwareElementType createModel_GreetingsAssignmentElementType() {
			return new IGrammarAwareElementType("Model_GreetingsAssignment_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getModelAccess().getGreetingsAssignment());
		}
		public static IGrammarAwareElementType createModel_GreetingsMyGreetingParserRuleCall_0ElementType() {
			return new IGrammarAwareElementType("Model_GreetingsMyGreetingParserRuleCall_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getModelAccess().getGreetingsMyGreetingParserRuleCall_0());
		}
	}

	public static final IGrammarAwareElementType Model_ELEMENT_TYPE = associate(ModelFactory.createModelElementType());

	public static final IGrammarAwareElementType Model_GreetingsAssignment_ELEMENT_TYPE = associate(ModelFactory.createModel_GreetingsAssignmentElementType());

	public static final IGrammarAwareElementType Model_GreetingsMyGreetingParserRuleCall_0_ELEMENT_TYPE = associate(ModelFactory.createModel_GreetingsMyGreetingParserRuleCall_0ElementType());

	private static class MyGreetingFactory {
		public static IGrammarAwareElementType createMyGreetingElementType() {
			return new IGrammarAwareElementType("MyGreeting_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getMyGreetingRule());
		}
		public static IGrammarAwareElementType createMyGreeting_GroupElementType() {
			return new IGrammarAwareElementType("MyGreeting_Group_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getMyGreetingAccess().getGroup());
		}
		public static IGrammarAwareElementType createMyGreeting_MydslKeyword_0ElementType() {
			return new IGrammarAwareElementType("MyGreeting_MydslKeyword_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getMyGreetingAccess().getMydslKeyword_0());
		}
		public static IGrammarAwareElementType createMyGreeting_NameAssignment_1ElementType() {
			return new IGrammarAwareElementType("MyGreeting_NameAssignment_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getMyGreetingAccess().getNameAssignment_1());
		}
		public static IGrammarAwareElementType createMyGreeting_NameIDTerminalRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("MyGreeting_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getMyGreetingAccess().getNameIDTerminalRuleCall_1_0());
		}
	}

	public static final IGrammarAwareElementType MyGreeting_ELEMENT_TYPE = associate(MyGreetingFactory.createMyGreetingElementType());

	public static final IGrammarAwareElementType MyGreeting_Group_ELEMENT_TYPE = associate(MyGreetingFactory.createMyGreeting_GroupElementType());

	public static final IGrammarAwareElementType MyGreeting_MydslKeyword_0_ELEMENT_TYPE = associate(MyGreetingFactory.createMyGreeting_MydslKeyword_0ElementType());

	public static final IGrammarAwareElementType MyGreeting_NameAssignment_1_ELEMENT_TYPE = associate(MyGreetingFactory.createMyGreeting_NameAssignment_1ElementType());

	public static final IGrammarAwareElementType MyGreeting_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE = associate(MyGreetingFactory.createMyGreeting_NameIDTerminalRuleCall_1_0ElementType());

	@Override
	public IFileElementType getFileType() {
		return FILE_TYPE;
	}

	@Override
	public IGrammarAwareElementType findElementType(EObject grammarElement) {
		return GRAMMAR_ELEMENT_TYPE.get(grammarElement);
	}
	
	public IGrammarAwareElementType getModelElementType() {
		return Model_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getModel_GreetingsAssignmentElementType() {
		return Model_GreetingsAssignment_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getModel_GreetingsMyGreetingParserRuleCall_0ElementType() {
		return Model_GreetingsMyGreetingParserRuleCall_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMyGreetingElementType() {
		return MyGreeting_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMyGreeting_GroupElementType() {
		return MyGreeting_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMyGreeting_MydslKeyword_0ElementType() {
		return MyGreeting_MydslKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMyGreeting_NameAssignment_1ElementType() {
		return MyGreeting_NameAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMyGreeting_NameIDTerminalRuleCall_1_0ElementType() {
		return MyGreeting_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE;
	}

}
