/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.ourdsl.idea.completion;

import org.eclipse.xtext.common.idea.completion.TerminalsCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractOurDslCompletionContributor extends TerminalsCompletionContributor {
	public AbstractOurDslCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
