/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.ourdsl.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class OurDslLanguage extends AbstractXtextLanguage{

	public static final OurDslLanguage INSTANCE = new OurDslLanguage();

	private OurDslLanguage() {
		super("org.xtext.example.ourdsl.OurDsl");
	}

}
