/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.ourdsl.idea.lang


class OurDslFileType extends AbstractOurDslFileType {
	public static final OurDslFileType INSTANCE = new OurDslFileType()
	
	new() {
		super(OurDslLanguage.INSTANCE)
	}
}
