/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.ourdsl.idea.lang.pom;

import org.eclipse.xtext.idea.pom.AbstractXtextPomDeclarationSearcher;
import org.xtext.example.ourdsl.idea.lang.OurDslLanguage;

public class OurDslPomDeclarationSearcher extends AbstractXtextPomDeclarationSearcher {
	public OurDslPomDeclarationSearcher() {
		super(OurDslLanguage.INSTANCE);
	}
}
