/*
 * generated by Xtext 2.9.0.beta5
 */
package org.xtext.example.yourdsl.idea.lang.pom;

import org.eclipse.xtext.idea.pom.AbstractXtextPomDeclarationSearcher;
import org.xtext.example.yourdsl.idea.lang.YourDslLanguage;

public class YourDslPomDeclarationSearcher extends AbstractXtextPomDeclarationSearcher {
	public YourDslPomDeclarationSearcher() {
		super(YourDslLanguage.INSTANCE);
	}
}
